/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphix;

import Player.PlayerDB;
import Player.Player;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IanGz
 *
 */
public class Graphix extends javax.swing.JFrame {

    /**
     * Creates new form Graphix
     */
    public Graphix() {
        initComponents();
        prueba();
    }

    public void prueba() {

        PlayerDB pdb = new PlayerDB();

        int maxHealth = pdb.DefineStats(ClassSelected.getSelectedIndex())[0];
        int def = pdb.DefineStats(ClassSelected.getSelectedIndex())[1];
        int atk = pdb.DefineStats(ClassSelected.getSelectedIndex())[2];
        int magic = pdb.DefineStats(ClassSelected.getSelectedIndex())[3];
        int dex = pdb.DefineStats(ClassSelected.getSelectedIndex())[4];
        int speed = pdb.DefineStats(ClassSelected.getSelectedIndex())[5];

        Player p = new Player(NameField.getText(), maxHealth, def, atk, magic, dex, speed);

        System.out.println(pdb.getPlayerClass(p) + "hola");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        StartGameB = new javax.swing.JButton();
        ExitGameB = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ClassSelected = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        SaveCharB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CharTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        DeleteCharB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartGameB.setText("Start Game");
        jPanel1.add(StartGameB);

        ExitGameB.setText("Exit");
        jPanel1.add(ExitGameB);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Name:");
        jPanel4.add(jLabel1);

        NameField.setColumns(10);
        NameField.setToolTipText("Introduce a name");
        NameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameFieldKeyPressed(evt);
            }
        });
        jPanel4.add(NameField);

        jLabel2.setText("Class:");
        jPanel4.add(jLabel2);

        ClassSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soldier", "Archer", "Mage", "Healer" }));
        jPanel4.add(ClassSelected);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        SaveCharB.setText("Save");
        SaveCharB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCharBActionPerformed(evt);
            }
        });
        jPanel5.add(SaveCharB);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Create character", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        CharTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CharTable);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        DeleteCharB.setText("Delete character");
        jPanel7.add(DeleteCharB);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Delete Character", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveCharBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCharBActionPerformed

        DefaultTableModel model = (DefaultTableModel) CharTable.getModel();

        PlayerDB pdb = new PlayerDB();

        if (!"".equals(NameField.getText())) {

            int maxHealth = pdb.DefineStats(ClassSelected.getSelectedIndex())[0];
            int def = pdb.DefineStats(ClassSelected.getSelectedIndex())[1];
            int atk = pdb.DefineStats(ClassSelected.getSelectedIndex())[2];
            int magic = pdb.DefineStats(ClassSelected.getSelectedIndex())[3];
            int dex = pdb.DefineStats(ClassSelected.getSelectedIndex())[4];
            int speed = pdb.DefineStats(ClassSelected.getSelectedIndex())[5];

            Player p = new Player(NameField.getText(), maxHealth, def, atk, magic, dex, speed);

            p.setType(ClassSelected.getSelectedIndex());

            model.addRow(new Object[]{p.getName(), pdb.getPlayerClass(p)});

        } else {

            JOptionPane.showMessageDialog(CharTable, "Pon un nombre");

        }


    }//GEN-LAST:event_SaveCharBActionPerformed

    private void NameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            SaveCharB.doClick();

        }


    }//GEN-LAST:event_NameFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphix().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CharTable;
    private javax.swing.JComboBox<String> ClassSelected;
    private javax.swing.JButton DeleteCharB;
    private javax.swing.JButton ExitGameB;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SaveCharB;
    private javax.swing.JButton StartGameB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
